### ISSUE TITLE
モデルコース カテゴリ一覧ページ 一覧部分スタイル

### ISSUE THREAD

**Issue by ha-ma** [malkinc/konkanren#14]
モデルコース カテゴリ一覧ページ 一覧部分スタイルをコース一覧ページと同様にする

**Comment by mayumi-S** [comment]
微調整により、若干スタイル変わってます。
私的にはモデルコースカテゴリ一覧のほうがよりXDに近い感じがするので、
未完のタブレット以降のボトムと合わせて、来週、コース一覧をこっちに近づける対応をしたいと思います。

**Comment by ha-ma** [comment]
@mayumi-S 
確認しました、細かいところまでご対応ありがとうございます。

> コース一覧をこっちに近づける

とありますが、
時間の関係上、微調整は私の方で行いますので
モデルコース一覧のスタイルをそのままモデルコースカテゴリページに適用する、
という方向で進めてください。
コピペ、スタイル名の変更で済むと思いますので、でき次第その時点でPRしてくだされば
mergeしますね。

なお、気になった点が一つありますので、（下記説明を読んで対応できそうであれば）そちらも対応後にPRお願いします。
**・hero画像を全幅にする**

⇛こちらは、coursescategory-headingをcoursescategory-containerと同階層にすると解決するはずです。やってみてわからなければ、そのままで良いのでPRしちゃってOKです

以上よろしくおねがいします！

**Comment by mayumi-S** [comment]
@ha-ma 
ごめんなさい、このコメント今気が付きました。
hero画像の件は明日出勤したらまず最初にやってPRします。

**Comment by mayumi-S** [comment]
hero画像全幅修正しました。pushしましたが、いつものPRのボタンが出てこないのは何故だらう。

**Comment by ha-ma** [comment]
@mayumi-S 
hero画像全幅対応ばっちりでした！
PRボタンでないのはSlackに理由書いたのでお時間あるときに読んでみてくださいね
おつかれさまです！
